"""empty message

Revision ID: dca1f4fe4688
Revises: 842ce9203d0b
Create Date: 2024-10-30 19:53:39.209957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca1f4fe4688'
down_revision = '842ce9203d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specie')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_specie_id_fkey', type_='foreignkey')
        batch_op.drop_column('specie_id')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_specie_id_fkey', type_='foreignkey')
        batch_op.drop_column('specie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specie_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorite_specie_id_fkey', 'specie', ['specie_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specie_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_specie_id_fkey', 'specie', ['specie_id'], ['id'])

    op.create_table('specie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='specie_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='specie_pkey')
    )
    # ### end Alembic commands ###
